name: Test C++

on: [push]

jobs:
  run-test:
    name: Test C++ on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: git pull submodules
        run: git submodule update --init --recursive

      # - name: install mkl
      #   run: ./scripts/install-mkl.sh
      # - name: install tbb
      #   run: ./scripts/install-tbb.sh

      - name: setup cmake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TEST=ON
      - name: run tests
        run: |
          cd build
          make
          ./run-test

  check-coverage:
    name: Check C++ coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git pull submodules
        run: git submodule update --init --recursive

      # - name: install mkl
      #   run: ./scripts/install-mkl.sh
      # - name: install tbb
      #   run: ./scripts/install-tbb.sh
      - name: install lcov
        run: sudo apt-get install lcov

      - name: setup cmake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TEST=ON -DBUILD_COVERAGE=ON
      - name: run tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd build
          make
          make coverage
          bash <(curl -s https://codecov.io/bash)
